apiVersion: v1
kind: Secret
metadata:
  name: symfony-api-secrets
type: Opaque
stringData:
  APP_SECRET: "change-me"
  DATABASE_HOST: "change-me"
  DATABASE_USER: "change-me"
  DATABASE_PASSWORD: "change-me"
  DATABASE_PORT: "change-me"
  MYSQL_ROOT_PASSWORD: "change-me"
  MYSQL_DATABASE: "change-me"
  MYSQL_USER: "change-me"
  MYSQL_PASSWORD: "change-me"
